/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core;

/**
 * An EmployeeEvaluation. 
 * The message is an employee evaluation that has been produced by an Actor
 * with the appropriate permissions. The message will contain the data being
 * evaluated. Evaluations are special with regard to how they are treated by
 * the system. They can only be generated by Supervisor or Manager users, 
 * are not interpreted by the system at all, can not be forwarded by any
 * non-Supervisor or Manager user, and attached to a single employee (the
 * one being evaluated). Once the evaluation is created, it is sent to the 
 * appropriate managers, and the employee being evaluated. From there, they
 * are signed off on by all parties, the evaluation data is placed in the 
 * appropriate place, and the message itself is cleared of the evaluation 
 * data. While the individual evaluations remain available to management
 * the employee record only notes the averages of the evaluations the 
 * employee has received.
 * @author odin
 */
public class EvaluationMessage extends Message {
    
}
